### ISSUE TITLE
Default message on Events page

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#38]
There won't always be events scheduled. Do we have a default message built that says something like 

"There are no events scheduled at this time. Please check back again."

**Comment by JuliaDickey** [comment]
Done. I added an else statement, so that message will appear when no events are in the database

**Comment by kelseyfriedman** [comment]
Thanks. Can you show me a screenshot of what this looks like since I can't see it right now?

**Comment by JuliaDickey** [comment]
Sure! You can play with this by adding or removing events in the admin portal. Just leave it blank when you're done since I'll be pushing database updates. 
<img width="1434" alt="screen shot 2017-03-03 at 10 17 07 am" src="https://cloud.githubusercontent.com/assets/19519395/23563266/c894808a-fffa-11e6-8b3f-7f6f464c7cd1.png">

**Comment by kelseyfriedman** [comment]
Perfect!
