### ISSUE TITLE
Build blog

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#4]
Include:
- [x] multiple photos
- [x] featured photo selection (auto crops so they are uniform on blog landing page)
- [x] text editor
- [x] Custom URLS or URLS auto-created by post title (rather than /post9 like it's doing now)

**Comment by kelseyfriedman** [comment]
@JuliaDickey I've shared a Google Doc with you that has the Tasiana blog post text. Here are the photos. When you're building the blog, please add this post as your test post - then you'll have the link for the other bugs. 

https://docs.google.com/document/d/1hlpzTau5dhfjdi88XVw-QP_OhTAD2aAMeBtPTNTD8yc/edit

![dsc02900](https://cloud.githubusercontent.com/assets/3065594/23448553/bd9ddf26-fe62-11e6-8dde-72b8d2ce7037.jpeg)
![dsc02903](https://cloud.githubusercontent.com/assets/3065594/23448554/bd9ff432-fe62-11e6-9f8c-edfeca7fd31f.jpeg)
![dsc04093](https://cloud.githubusercontent.com/assets/3065594/23448555/bda5c2f4-fe62-11e6-90d1-2b4bd5021b3b.jpeg)
![screen shot 2015-10-06 at 6 56 55 am](https://cloud.githubusercontent.com/assets/3065594/23448556/bda9905a-fe62-11e6-9f2d-8bc40b6b113d.png)

**Comment by JuliaDickey** [comment]
The blog is up. Working on adding gallery of photos and custom URLs

**Comment by JuliaDickey** [comment]
Custom URLs are done. Adding gallery today.

**Comment by kelseyfriedman** [comment]
Love the blog landing page! It's so clean and I love the sidebar menu! I didn't have time to add any new posts because the images need to be resized for web and I don't have time to do that today - Pole! Thanks for offering to add the content. I'm going to write a new post next week about the Kili 5k and I will add that one so I can practice using the dashboard. 

- [ ] We need to be able to change the date on posts. For example, Tasiana's story was written in 2016 and needs to be the oldest one in the blog list. Can we add a field for a custom date? 

- [ ] For the featured image, it's great that it's cropped to the same size on the landing page, but can we have it crop on the top of the blog as well, for consistency? On this post it's a different dimension https://intense-spire-56347.herokuapp.com/blog/when-the-moon-hits-your-eye-it-hurts than this one https://intense-spire-56347.herokuapp.com/blog/tasiana-kicks

- [ ] Why do these two look so different? the side columns are hugely different https://intense-spire-56347.herokuapp.com/blog/tasiana-kicks and https://intense-spire-56347.herokuapp.com/blog/tasiana

- [ ] When I edited a blog post, the changes I made appeared to occur when I clicked 'update" but the modal didn't close.

**Comment by JuliaDickey** [comment]
They look different because there is so much less copy. Since the copy isn't filling the page, the width is smaller. I could make a minimum width on desktop if it bugs you.

**Comment by JuliaDickey** [comment]
I can't crop the images to the same size, and have them work as responsive images. I can ask one of my teachers at Epicodus tomorrow and see if they have any ideas.

**Comment by JuliaDickey** [comment]
A zoomable gallery is up! The tasiana photos are so small that they don't scale up, but the others do.

**Comment by kelseyfriedman** [comment]
Yayyy!!!! This looks great! I love it!!!

Honestly I think the Tasiana photos are fine. It's an old story and I'm not too worried about those photos. 

On the other stories the photos aren't zoomable for me though? I'm on chrome and when i hover I get a cursor but I can't actually click the photos.

**Comment by JuliaDickey** [comment]
Fixed the zoom issue.

**Comment by kelseyfriedman** [comment]
Cool! I like it. 

I think a nice to have in the future is that the gallery is scrollable so I can go through the photos all at once without closing each one, but this is great for now! 

Great job with the blog. It looks really really great! Closing this

**Comment by kelseyfriedman** [comment]
Zoom is broken again

**Comment by kelseyfriedman** [comment]
Looks like it's working now! I did notice that the images aren't all cropping the same in the gallery. Any idea why? One of the 5 is a different dimension... does it keep the original dimensions and I cropped it weird or something? I don't think I cropped any of these....

https://intense-spire-56347.herokuapp.com/blog/volunteer-service-trips-improve-the-health-of-our-students-and-campus

**Comment by JuliaDickey** [comment]
I can't display one dimension, then zoom another. I tried :(. 

I did fix the images so they are cropping to 600x400 with focus on faces. Cloudinary has face-detection. Boom! Done :)

**Comment by kelseyfriedman** [comment]
Perfect. I'd rather them crop and be the same size. Thanks!
