### ISSUE TITLE
Edit Our Story doc and send to Kristi

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#6]

**Comment by kelseyfriedman** [comment]
Assigning to myself and moving back to In Progress. Once Ashley sends final edits I will reassign to you to update the text.

**Comment by kelseyfriedman** [comment]
This is ready for you and Kristi to finalize and put on the site. See email for details

**Comment by JuliaDickey** [comment]
Awesome. Added Our Story updates. Let me know what you think of the CTA.

**Comment by kelseyfriedman** [comment]
Our Story
- [ ] The font changes size after the first sentence. Not sure if that's intentional or just some html in the way
- [ ] Love the pull quote style! We should attribute it to Ashley so people know it's her. 

Timeline
- [ ] Please see document comments for a couple small edits/responses. https://docs.google.com/document/d/1o6JmYuSXBYiC9N-IEAlGaVJyku6zNHtBVOR-Z1udEh4/edit
- [ ] April-June 2011 entry needs a break between graphs
- [ ] I don't think there should be a CTA breaking the two sections. I'm guessing this is in place of Kristi's line about "joining us in giving a red sweater" but I think using the CTA makes it look like the bottom of the page since across all other pages, that CTA banner is an indicator of the bottom of the page. I think we should just have the one at the bottom and go straight to the Timeline. Perhaps we can add some of the other photos Ashley sent if you're looking for a visual?

**Comment by kelseyfriedman** [comment]
- [ ] Please see google doc again for one edit. There was a space missing in one of the new entries. 
- [ ] I don't think there should be commas between month and year. Do you want to ask your copy editors about that and let me know? I think without a day the comma is wrong but maybe I'm wrong?

**Comment by JuliaDickey** [comment]
Done! :)
